class OttoException(Exception):
    """Exception within otto"""
